name: Document with Slither

on:
  pull_request:
    types: [labeled]
    branches: [main]

jobs:
  document:
    name: Document with Slither
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'generate-docs')
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: project
        run: npm ci

      - name: Document with Slither
        uses: crytic/slither-docs-action@v0
        with:
          target: project
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
